/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

void delay(int a)
{
	for(int i=0; i<= (571700*a); i++);
}

#include "stm32f407xx.h"

int main(void)
{

	GPIO_Handle_t gpioled;

	gpioled.pGPIOx = GPIOD;
	gpioled.PinConfig.pinNumber = GPIO_PIN_NO_13;
	gpioled.PinConfig.PinMode = PIN_MODE_OUT;
	gpioled.PinConfig.PinOType = PIN_OTYPE_PP;
	gpioled.PinConfig.PinOSpeed = PIN_OSPEED_HIGH;
	gpioled.PinConfig.PinPuPd = PIN_PUPD_NONE;

	GPIO_PeriClkControl(GPIOD, ENABLE);
	GPIO_Init(gpioled);

	while(1)
	{
	GPIO_TogglePin(GPIOD, GPIO_PIN_NO_13);
	delay(2);
	}


}
